import { capsuleTimelineStyles } from './timeline-styles.js';
import { capsuleWorkspaceStyles } from './workspace-styles.js';

/** Local tokens, font stack and shell geometry from the supplied report mockup. */
export const capsuleReportStyles = `
.capsule-view{--page:#101114;--rail:#141519;--surface:#191a20;--raised:#202128;--line:#2b2d36;--line2:#3c3f49;--text:#f1f1f5;--muted:#a4a6b4;--dim:#858894;--pink:#ef4779;--pink-soft:#f6a3ba;--pink-bg:#34202b;--green:#91d5b5;--red:#f29aa3;--amber:#e9c080;--mono:ui-monospace,SFMono-Regular,Consolas,'Liberation Mono',monospace;display:grid;grid-template-columns:226px minmax(0,1fr);min-width:0;color:var(--text);background:var(--page);font:16px/1.65 Inter,ui-sans-serif,system-ui,-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;letter-spacing:-.012em}
.capsule-view *{box-sizing:border-box}.capsule-view [hidden]{display:none!important}.capsule-view :is(button,a,summary):focus-visible{outline:2px solid var(--pink-soft);outline-offset:3px}.capsule-view button{font:inherit;cursor:pointer}.capsule-view p{margin:0}.capsule-view p+p{margin-top:10px}.capsule-view h1,.capsule-view h2,.capsule-view h3{margin:0;font-weight:620}.capsule-view .icon{width:18px;height:18px;flex:none;fill:none;stroke:currentColor;stroke-width:1.6;stroke-linecap:round;stroke-linejoin:round}.capsule-view .muted{color:var(--muted)}
.capsule-view .report-rail{position:sticky;top:0;height:100vh;padding:25px 12px 18px;border-right:1px solid var(--line);background:var(--rail);display:flex;flex-direction:column}.capsule-view .report-brand{display:flex;align-items:center;gap:10px;padding:0 10px 24px;font-size:22px;letter-spacing:-.7px}.capsule-view .report-brand .icon{width:30px;height:30px;color:var(--pink)}.capsule-view .project-box{display:flex;gap:9px;align-items:center;padding:0 10px 20px;overflow-wrap:anywhere}.capsule-view .rail-label{margin:17px 10px 9px;color:var(--dim);font-size:12px;text-transform:uppercase;letter-spacing:1.3px}.capsule-view .report-rail a{display:flex;align-items:center;gap:10px;min-height:46px;padding:10px 11px;margin:2px 0;border-radius:6px;color:var(--muted);text-decoration:none;font-size:15px}.capsule-view .report-rail a:hover{background:var(--raised);color:var(--text)}.capsule-view .report-rail a.active{background:var(--pink-bg);color:var(--pink-soft)}.capsule-view .nav-label{flex:1}.capsule-view .nav-count{color:var(--dim);font:12px var(--mono)}.capsule-view .rail-footer{margin-top:auto;padding:24px 8px 0;color:var(--dim);font-size:12px}
.capsule-view .report-main{min-width:0}.capsule-view .report-topbar{display:flex;align-items:center;gap:12px;height:66px;padding:0 34px;border-bottom:1px solid var(--line);color:var(--muted);font-size:14px}.capsule-view .report-topbar strong{font-weight:500;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.capsule-view .report-topbar .badge{margin-left:auto}.capsule-view .report-content{padding:34px;max-width:1680px;margin:auto}.capsule-view .report-hero{padding:0}.capsule-view .eyebrow{color:var(--muted);font-size:12px;font-weight:650;text-transform:uppercase;letter-spacing:1.6px;margin:0 0 10px}.capsule-view .report-hero h1{font-size:clamp(32px,3.6vw,52px);line-height:1.18;letter-spacing:-1.05px;overflow-wrap:anywhere}.capsule-view .session-id{font:13px var(--mono);color:var(--dim);margin-top:14px;overflow-wrap:anywhere}.capsule-view .lede{max-width:900px;color:var(--muted);margin-top:16px;font-size:18px;line-height:1.7}.capsule-view .hero-meta{display:flex;flex-wrap:wrap;gap:10px 24px;margin-top:18px;font-size:13px;color:var(--dim)}.capsule-view .hero-meta strong{color:var(--muted);font-weight:500}
.capsule-view .metrics{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));margin-top:28px;border:1px solid var(--line);border-radius:9px;background:var(--surface);overflow:hidden}.capsule-view .metric{padding:17px 20px;border-left:1px solid var(--line)}.capsule-view .metric:first-child{border:0}.capsule-view .metric strong{display:block;font-size:30px;line-height:1.4;font-weight:600}.capsule-view .metric span{font-size:14px;color:var(--muted)}.capsule-view .report-notice{display:flex;align-items:center;gap:12px;padding:15px 18px;margin:20px 0 26px;border:1px solid #493443;background:#211b22;border-radius:8px;color:var(--muted);font-size:14px}.capsule-view .report-notice .icon{color:var(--pink-soft)}
${capsuleWorkspaceStyles}
${capsuleTimelineStyles}
@media(max-width:1240px){.capsule-view{grid-template-columns:200px minmax(0,1fr)}.capsule-view .report-content{padding:26px 24px}.capsule-view .report-workspace{grid-template-columns:minmax(0,1fr) 290px;gap:16px}}
@media(max-width:1030px){.capsule-view .report-workspace{grid-template-columns:1fr}.capsule-view .report-inspector{position:static}.capsule-view .inspector-body{max-height:none}.capsule-view .resource-grid{grid-template-columns:1fr}}
@media(max-width:720px){.capsule-view{display:block}.capsule-view .report-rail{position:static;height:auto;display:flex;flex-direction:row;overflow:auto;padding:8px;border-right:0;border-bottom:1px solid var(--line)}.capsule-view .report-rail a{flex:none;font-size:14px}.capsule-view .report-brand,.capsule-view .project-box,.capsule-view .rail-label,.capsule-view .rail-footer{display:none}.capsule-view .report-topbar{height:56px;padding:0 16px}.capsule-view .report-content{padding:24px 16px}.capsule-view .report-hero h1{font-size:32px}.capsule-view .metrics{grid-template-columns:repeat(2,minmax(0,1fr))}.capsule-view .metric:nth-child(n+3){border-top:1px solid var(--line)}.capsule-view .metric:nth-child(3){border-left:0}.capsule-view .summary-grid{grid-template-columns:1fr}.capsule-view .activity summary{grid-template-columns:32px minmax(0,1fr) 16px;padding:13px;gap:8px}.capsule-view .activity-badges{grid-column:2;grid-row:2;justify-content:flex-start}.capsule-view .activity summary>.icon{grid-column:3;grid-row:1}.capsule-view .activity-body{padding:14px}.capsule-view .span-row{flex-wrap:wrap}.capsule-view .section-head{display:block}.capsule-view .section-head>p{margin-top:8px}.capsule-view .placeholder{display:block}}
@media(prefers-reduced-motion:reduce){.capsule-view *{scroll-behavior:auto!important;transition:none!important}}
@media print{.capsule-view{display:block}.capsule-view .report-rail,.capsule-view .report-topbar{display:none}.capsule-view .report-workspace{display:block}.capsule-view .workspace-content>section[hidden]{display:block!important}.capsule-view .activity{break-inside:avoid}}
`;
