// Generic polling and navigation. Provider client views own report interpretation and DOM.
export const REGISTRY_SCRIPT = `
const elements={list:document.getElementById('reports'),status:document.getElementById('status'),detailStatus:document.getElementById('detail-status'),report:document.getElementById('report'),empty:document.getElementById('empty'),search:document.getElementById('search'),sort:document.getElementById('sort')};
const state={selection:null,reports:[],registryBytes:'',reportBytes:'',filter:'all',search:'',sort:'newest',refreshing:false,timer:null,request:null,revision:0,reportStates:new Map()};
const key=value=>value.type+':'+value.id;const failed=value=>value==='failed'||value.endsWith('-failed');
function selectionFromUrl(){const query=new URL(location.href).searchParams;return query.has('type')&&query.has('id')?{type:query.get('type'),id:query.get('id')}:null}
function matches(report){const filter=state.filter==='all'||(state.filter==='failed'?failed(report.state):report.state===state.filter);const description=report.description.kind==='available'?report.description.value:'';return filter&&[report.title,report.id,report.type,report.state,description].join(' ').toLowerCase().includes(state.search.toLowerCase())}
function sortedReports(){const reports=state.reports.filter(matches);reports.sort((a,b)=>state.sort==='title'?a.title.localeCompare(b.title):(state.sort==='oldest'?1:-1)*(Date.parse(a.createdAt)-Date.parse(b.createdAt)));return reports}
function text(tag,className,value){const node=document.createElement(tag);node.className=className;node.textContent=value;return node}
function reportLink(report){const li=document.createElement('li'),link=document.createElement('a');link.className='report-link';link.href='?'+new URLSearchParams({type:report.type,id:report.id});link.setAttribute('aria-current',String(state.selection!==null&&key(state.selection)===key(report)));const dot=text('span','state-dot '+report.state,'');dot.setAttribute('aria-hidden','true');const body=document.createElement('span');body.append(text('span','report-title',report.title),text('span','report-id',report.id+' · '+report.type));if(report.description.kind==='available')body.append(text('span','report-desc',report.description.value));const side=document.createElement('span');side.append(text('span','report-state',report.state),text('span','report-id',new Date(report.createdAt).toLocaleString()));link.append(dot,body,side);link.addEventListener('click',event=>{event.preventDefault();navigate({type:report.type,id:report.id})});li.append(link);return li}
function renderList(){const reports=sortedReports();elements.list.replaceChildren(...reports.map(reportLink));document.getElementById('result-count').textContent=reports.length+' of '+state.reports.length+' experiments';if(!reports.length)elements.list.append(text('li','registry-empty','No matching experiments. Change the search or state filter.'));for(const [id,count] of [['total-count',state.reports.length],['running-count',state.reports.filter(item=>item.state==='running').length],['stopped-count',state.reports.filter(item=>item.state==='stopped').length],['failed-count',state.reports.filter(item=>failed(item.state)).length]])document.getElementById(id).textContent=String(count)}
function captureReportState(){if(state.selection===null)return;state.reportStates.set(key(state.selection),{open:[...elements.report.querySelectorAll('details[open]')].map(node=>node.id),scrollY,section:location.hash.slice(1)})}
function setSelection(selection){captureReportState();state.request?.abort();state.request=null;state.selection=selection;state.reportBytes='';state.revision+=1;elements.report.hidden=true;elements.report.replaceChildren();elements.empty.hidden=selection!==null;elements.detailStatus.textContent=selection===null?'':'Loading '+selection.id+'…';renderList()}
function navigate(selection){const url=new URL(location.href);url.hash='';url.search=selection===null?'':new URLSearchParams({type:selection.type,id:selection.id});history.pushState(null,'',url);setSelection(selection);void refresh()}
async function read(url,signal){const response=await fetch(url,{cache:'no-store',signal:signal??AbortSignal.timeout(5000)});if(!response.ok)throw new Error('Request failed ('+response.status+')');return response}
async function refreshRegistry(){try{const data=await(await read('/api/reports')).json(),bytes=JSON.stringify(data);if(bytes!==state.registryBytes){state.reports=data.reports;state.registryBytes=bytes;renderList()}elements.status.textContent='Connected · '+data.reports.length+' sessions · checked '+new Date().toLocaleTimeString()+(data.failures.length?' · '+data.failures.length+' provider failures':'')}catch{elements.status.textContent='Updates unavailable. Displayed sessions may be stale. Retrying…'}}
function renderDocument(current,document,bytes){const view=BlackboxReportViews[current.type];if(!view||typeof view.render!=='function')throw new Error('No compatible report view.');const saved=state.reportStates.get(key(current))||{open:[],section:location.hash.slice(1)};const y=scrollY;view.render(elements.report,document,saved);state.reportBytes=bytes;elements.report.hidden=false;elements.empty.hidden=true;requestAnimationFrame(()=>{if(state.selection===current)scrollTo(0,y)})}
async function refreshReport(){const current=state.selection;if(current===null)return;const revision=state.revision;state.request?.abort();const controller=new AbortController();state.request=controller;try{const result=await(await read('/api/reports/'+encodeURIComponent(current.type)+'/'+encodeURIComponent(current.id),controller.signal)).json();if(revision!==state.revision||current!==state.selection)return;if(result.kind!=='report-document')throw new Error('Invalid report response.');const bytes=JSON.stringify(result.document);if(bytes!==state.reportBytes)renderDocument(current,result.document,bytes);elements.detailStatus.textContent='Following '+current.id+' · recorded updates refresh automatically'}catch(error){if(controller.signal.aborted||revision!==state.revision)return;elements.detailStatus.textContent='Cannot update '+current.id+'. '+(state.reportBytes?'Showing the last snapshot; it may be stale.':'No compatible report is available.')+' Retrying…'}finally{if(state.request===controller)state.request=null}}
async function refresh(){if(state.refreshing)return;clearTimeout(state.timer);state.refreshing=true;try{await Promise.all([refreshRegistry(),refreshReport()])}finally{state.refreshing=false;state.timer=setTimeout(refresh,1000)}}
document.getElementById('refresh').addEventListener('click',()=>void refresh());elements.search.addEventListener('input',event=>{state.search=event.target.value;renderList()});elements.sort.addEventListener('change',event=>{state.sort=event.target.value;renderList()});document.addEventListener('click',event=>{const button=event.target.closest('[data-filter]');if(!button)return;state.filter=button.dataset.filter;for(const item of document.querySelectorAll('[data-filter]'))item.setAttribute('aria-pressed',String(item===button));renderList()});addEventListener('popstate',()=>{setSelection(selectionFromUrl());void refresh()});
setSelection(selectionFromUrl());void refresh();
`;
