import type {
  FeaturePlan,
  PlannedBackground,
  PlannedRule,
  PlannedScenario,
  PlannedStep,
} from './planning/model.js';

export interface EmitInput {
  readonly plan: FeaturePlan;
  /** The `.feature` path relative to the generated file, with `/` separators. */
  readonly featureFromOutput: string;
  /** Module the generated file imports its runtime from. */
  readonly runtimeModule: string;
  readonly featureHash: string;
  readonly vocabularyHash: string;
}

const q = (value: unknown): string => JSON.stringify(value);

function fixtureNames(steps: readonly PlannedStep[]): readonly string[] {
  return [...new Set(steps.flatMap((step) => step.definition.fixtures))].sort();
}

/**
 * The body every hook and test shares. Only the fixtures its steps declare are
 * destructured, so Playwright never starts one (such as a browser) that no
 * step reads; the Blackbox attempt fixture is automatic either way.
 */
function body(steps: readonly PlannedStep[], pad: string): readonly string[] {
  const names = fixtureNames(steps).join(', ');
  return [
    `async (${names.length === 0 ? '' : `{ ${names} }`}) => {`,
    `${pad}  const fixtures = { ${names} };`,
    ...steps.map(
      (step) =>
        `${pad}  await runStep(fixtures, { feature, line: ${step.line}, column: ${step.column}, keyword: ${q(step.keyword)} }, ${q(step.text)}, ${q(step.argument)});`,
    ),
    `${pad}});`,
  ];
}

function emitBackground(background: PlannedBackground | null, pad: string): readonly string[] {
  if (background === null) {
    return [];
  }
  // Attempt-scoped: Background runs inside every trial, never in beforeAll.
  const [first, ...rest] = body(background.steps, pad);
  return [`${pad}suite.beforeEach("Background", ${first}`, ...rest];
}

function emitScenario(scenario: PlannedScenario, pad: string): readonly string[] {
  // Requirement IDs are annotations only: they never select, skip or change a verdict.
  const annotation = scenario.requirements.map((id) => ({ type: 'requirement', description: id }));
  const [first, ...rest] = body(scenario.steps, pad);
  return [`${pad}suite.test(${q(scenario.title)}, { annotation: ${q(annotation)} }, ${first}`, ...rest];
}

function emitScope(
  scope: { readonly background: PlannedBackground | null; readonly scenarios: readonly PlannedScenario[] },
  pad: string,
): readonly string[] {
  return [
    ...emitBackground(scope.background, pad),
    ...scope.scenarios.flatMap((scenario) => emitScenario(scenario, pad)),
  ];
}

function emitRule(rule: PlannedRule, pad: string): readonly string[] {
  return [`${pad}suite.describe(${q(rule.title)}, () => {`, ...emitScope(rule, `${pad}  `), `${pad}});`];
}

/**
 * Emits one ES module that declares the feature through the public
 * `test.system(...).sandbox(...)` facade. It never emits test.only, skip,
 * fixme, fail, slow, setTimeout or describe.configure.
 */
export function emitFeature(input: EmitInput): string {
  const { plan } = input;
  const { kind, id, sandbox } = plan.selection;
  const pad = '      ';
  return [
    `// Generated by @suites/blackbox-gherkin from ${q(plan.file)}. Do not edit; recompile instead.`,
    `// feature ${input.featureHash}; step library ${input.vocabularyHash}`,
    `import { runStep, sandboxEnvironment, test } from ${q(input.runtimeModule)};`,
    '',
    `const feature = new URL(${q(input.featureFromOutput)}, import.meta.url);`,
    '',
    `test.system(${q({ kind, id })}, (system) => {`,
    `  system.sandbox(${q(sandbox)}, { environment: sandboxEnvironment(${q(plan.environment)}) }, (suite) => {`,
    `    suite.describe(${q(plan.title)}, () => {`,
    ...emitScope(plan, pad),
    ...plan.rules.flatMap((rule) => emitRule(rule, pad)),
    '    });',
    '  });',
    '});',
    '',
  ].join('\n');
}
