import type { SandboxCredentialSpec } from '../runtime/credentials.js';
import type {
  FeaturePlan,
  PlannedBackground,
  PlannedRule,
  PlannedScenario,
  PlannedStep,
} from './planning/model.js';

export interface EmitInput {
  readonly plan: FeaturePlan;
  /** The `.feature` path relative to the generated file, with `/` separators. */
  readonly featureFromOutput: string;
  /** Module the generated file imports its runtime from. */
  readonly runtimeModule: string;
  readonly featureHash: string;
  readonly vocabularyHash: string;
}

const q = (value: unknown): string => JSON.stringify(value);

// Credentials come from the Sandbox profile through the generated file, not from Playwright.
const CREDENTIALS = 'credentials';

function fixtureNames(steps: readonly PlannedStep[]): readonly string[] {
  return [...new Set(steps.flatMap((step) => step.definition.fixtures))].sort();
}

/**
 * The body every hook and test shares. Only the fixtures its steps declare are
 * destructured, so Playwright never starts one (such as a browser) that no
 * step reads; the Blackbox attempt fixture is automatic either way.
 */
function body(steps: readonly PlannedStep[], pad: string): readonly string[] {
  const names = fixtureNames(steps);
  const native = names.filter((name) => name !== CREDENTIALS).join(', ');
  return [
    `async (${native.length === 0 ? '' : `{ ${native} }`}) => {`,
    `${pad}  const fixtures = { ${names.join(', ')} };`,
    ...steps.map(
      (step) =>
        `${pad}  await runStep(fixtures, { feature, line: ${step.line}, column: ${step.column}, keyword: ${q(step.keyword)} }, ${q(step.text)}, ${q(step.argument)});`,
    ),
    `${pad}});`,
  ];
}

function emitBackground(background: PlannedBackground | null, pad: string): readonly string[] {
  if (background === null) {
    return [];
  }
  // Attempt-scoped: Background runs inside every trial, never in beforeAll.
  const [first, ...rest] = body(background.steps, pad);
  return [`${pad}suite.beforeEach("Background", ${first}`, ...rest];
}

function emitScenario(scenario: PlannedScenario, pad: string): readonly string[] {
  // Requirement IDs are annotations only: they never select, skip or change a verdict.
  const annotation = scenario.requirements.map((id) => ({ type: 'requirement', description: id }));
  const [first, ...rest] = body(scenario.steps, pad);
  return [`${pad}suite.test(${q(scenario.title)}, { annotation: ${q(annotation)} }, ${first}`, ...rest];
}

function emitScope(
  scope: { readonly background: PlannedBackground | null; readonly scenarios: readonly PlannedScenario[] },
  pad: string,
): readonly string[] {
  return [
    ...emitBackground(scope.background, pad),
    ...scope.scenarios.flatMap((scenario) => emitScenario(scenario, pad)),
  ];
}

function emitRule(rule: PlannedRule, pad: string): readonly string[] {
  return [`${pad}suite.describe(${q(rule.title)}, () => {`, ...emitScope(rule, `${pad}  `), `${pad}});`];
}

function allSteps(plan: FeaturePlan): readonly PlannedStep[] {
  const scopes = [plan, ...plan.rules];
  return scopes.flatMap((scope) => [
    ...(scope.background === null ? [] : scope.background.steps),
    ...scope.scenarios.flatMap((scenario) => scenario.steps),
  ]);
}

/**
 * The profile credentials the feature's steps name, or null when no step reads
 * credentials. Only the named ones are read from the runner environment.
 */
function usedCredentials(plan: FeaturePlan): SandboxCredentialSpec | null {
  const steps = allSteps(plan);
  if (!steps.some((step) => step.definition.fixtures.includes(CREDENTIALS))) {
    return null;
  }
  const names = new Set(
    steps.flatMap((step) => {
      const index = step.definition.credentialParameter;
      return index === null ? [] : [String(step.parameters[index])];
    }),
  );
  return Object.fromEntries([...names].sort().map((name) => [name, plan.credentials[name]] as const));
}

/**
 * Emits one ES module that declares the feature through the public
 * `test.system(...).sandbox(...)` facade. It never emits test.only, skip,
 * fixme, fail, slow, setTimeout or describe.configure.
 */
export function emitFeature(input: EmitInput): string {
  const { plan } = input;
  const { kind, id, sandbox } = plan.selection;
  const pad = '      ';
  const credentials = usedCredentials(plan);
  const runtime = ['runStep', ...(credentials === null ? [] : ['sandboxCredentials']), 'sandboxEnvironment', 'test'];
  return [
    `// Generated by @suites/blackbox-gherkin from ${q(plan.file)}. Do not edit; recompile instead.`,
    `// feature ${input.featureHash}; step library ${input.vocabularyHash}`,
    `import { ${runtime.join(', ')} } from ${q(input.runtimeModule)};`,
    '',
    `const feature = new URL(${q(input.featureFromOutput)}, import.meta.url);`,
    // Read when the file loads, as the Sandbox environment is; names variables, never values.
    ...(credentials === null ? [] : [`const ${CREDENTIALS} = sandboxCredentials(${q(credentials)});`]),
    '',
    `test.system(${q({ kind, id })}, (system) => {`,
    `  system.sandbox(${q(sandbox)}, { environment: sandboxEnvironment(${q(plan.environment)}) }, (suite) => {`,
    `    suite.describe(${q(plan.title)}, () => {`,
    ...emitScope(plan, pad),
    ...plan.rules.flatMap((rule) => emitRule(rule, pad)),
    '    });',
    '  });',
    '});',
    '',
  ].join('\n');
}
